### ISSUE TITLE
Error: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by sereysethy** [deroux/longitudinal-analysis-cowrie#1]
Hi,

Thanks for this great tool, but I failed to produce what you described in the readme.

Whenever I ran your program, I got this error: `unsupported operand type(s) for +: 'NoneType' and 'str'`

I only got to see this image which is similar to your [image](https://github.com/deroux/longitudinal-analysis-cowrie/blob/main/cowralyze/example_outputs/statistics.png).

**Comment by deroux** [comment]
Hi, 
can you please describe the steps to reproduce the issue? 
Which command are you trying to execute and on which files / folder content? Or on a remote host? 

Kind regards

**Comment by sereysethy** [comment]
I started with this

```
python cowralyze.py analyze-local -p to_log_folder
```

I already got an aforementioned error.

Then each time I ran the other commands, I always got the same error.

```
python cowralyze.py visualize --logfile reduced.json
```

But this one had no error:

```
python cowralyze.py statistics --logfile reduced.json
```

I am not sure maybe because my `cowrie.json` contains some other information because I did modify cowrie to include other things.

**Comment by sereysethy** [comment]
```shell
$ python cowralyze.py visualize --logfile reduced.json 
                                 __               
  _________ _      ___________ _/ /_  ______  ___ 
 / ___/ __ \ | /| / / ___/ __ `/ / / / /_  / / _ \
/ /__/ /_/ / |/ |/ / /  / /_/ / / /_/ / / /_/  __/
\___/\____/|__/|__/_/   \__,_/_/\__, / /___/\___/ 
                               /____/             

unsupported operand type(s) for +: 'NoneType' and 'str'
[19:54:00] reduced.json                                                                                                                                                    table.py:18
created stats.html
```

**Comment by deroux** [comment]
Thank you for your detailed description.
I will look into this error and try to reproduce, could you please provide your reduced.json file? (maybe on slack or just post it here) 

Please be sure to only keep files like in the example_logs folder in your analyzed folder, then everything should work like expected as can be seen in the image. You can just try to run a local analysis with the example_logs folder to check if your setup is working as intended. 

The warning message might though provide a proper analyzation result. 

<img width="682" alt="Bildschirmfoto 2021-09-30 um 22 35 57" src="https://user-images.githubusercontent.com/22377333/135526835-3bc46ee2-a1b6-4a41-a04f-4b97d87dda5a.png">

<img width="682" alt="Bildschirmfoto 2021-09-30 um 22 39 57" src="https://user-images.githubusercontent.com/22377333/135527125-d20389fd-17c6-4d95-b278-88777dc40a60.png">
